# -*- mode: ruby -*- 
# vi: set ft=ruby : 
Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-20.04"
      
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    config.vm.hostname = "Bootstrap-vm"
    config.ssh.forward_agent = true
  
    config.vm.synced_folder "../..", "/home/vagrant/dev", mount_options: ["fmode=744,dmode=755"]
  
    config.vm.provision "shell", privileged: false do |s|
      ssh_prv_key = ""
      ssh_pub_key = ""
      SSH_KEYNAME = ENV['SSH_KEYNAME'] || 'id_rsa'
  
      if ! File.file?("#{Dir.home}/.ssh/#{SSH_KEYNAME}")
        s.inline = "echo 'No SSH key found. You will need to remedy this before pushing to the repository.'"
  
      else
        ssh_prv_key = File.read("#{Dir.home}/.ssh/#{SSH_KEYNAME}")
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/#{SSH_KEYNAME}.pub").first.strip
  
        s.inline = <<-SHELL
          if grep -sq "#{ssh_pub_key}" $HOME/.ssh/authorized_keys; then
            echo "SSH keys already provisioned."
            exit 0;
          fi
          echo "SSH key provisioning."
          ssh_path=$(dirname $HOME/.ssh/#{SSH_KEYNAME})
          mkdir -p $ssh_path
          chmod 700 $HOME/.ssh/
          touch $HOME/.ssh/authorized_keys
          echo #{ssh_pub_key} >> $HOME/.ssh/authorized_keys
          echo #{ssh_pub_key} > $HOME/.ssh/#{SSH_KEYNAME}.pub
          chmod 644 $HOME/.ssh/#{SSH_KEYNAME}.pub
          echo "#{ssh_prv_key}" > $HOME/.ssh/#{SSH_KEYNAME}
          chmod 600 $HOME/.ssh/#{SSH_KEYNAME}
          echo "Type 'ssh-add ~/.ssh/#{SSH_KEYNAME}' to add the key to the VM"
          exit 0
        SHELL
      end
    end
  end